ai_task:
- generate_data
- generate_image
alarm_control_panel:
- alarm_arm_away
- alarm_arm_custom_bypass
- alarm_arm_home
- alarm_arm_night
- alarm_arm_vacation
- alarm_disarm
- alarm_trigger
automation:
- reload
- toggle
- trigger
- turn_off
- turn_on
backup:
- create_automatic
button:
- press
camera:
- disable_motion_detection
- enable_motion_detection
- play_stream
- record
- snapshot
- turn_off
- turn_on
climate:
- set_fan_mode
- set_humidity
- set_hvac_mode
- set_preset_mode
- set_swing_horizontal_mode
- set_swing_mode
- set_temperature
- toggle
- turn_off
- turn_on
cloud:
- remote_connect
- remote_disconnect
conversation:
- process
- reload
counter:
- decrement
- increment
- reset
- set_value
cover:
- close_cover
- close_cover_tilt
- open_cover
- open_cover_tilt
- set_cover_position
- set_cover_tilt_position
- stop_cover
- stop_cover_tilt
- toggle
- toggle_cover_tilt
device_tracker:
- see
dreame_vacuum:
- select_select_first
- select_select_last
- select_select_next
- select_select_previous
- update
- vacuum_backup_map
- vacuum_call_action
- vacuum_clean_segment
- vacuum_clean_spot
- vacuum_clean_zone
- vacuum_delete_map
- vacuum_discard_temporary_map
- vacuum_follow_path
- vacuum_goto
- vacuum_install_voice_pack
- vacuum_merge_segments
- vacuum_remote_control_move_step
- vacuum_rename_map
- vacuum_rename_segment
- vacuum_rename_shortcut
- vacuum_replace_temporary_map
- vacuum_request_map
- vacuum_reset_consumable
- vacuum_restore_map
- vacuum_restore_map_from_file
- vacuum_save_temporary_map
- vacuum_select_map
- vacuum_set_carpet_area
- vacuum_set_cleaning_sequence
- vacuum_set_custom_carpet_cleaning
- vacuum_set_custom_cleaning
- vacuum_set_obstacle_ignore
- vacuum_set_predefined_points
- vacuum_set_property
- vacuum_set_restricted_zone
- vacuum_set_router_position
- vacuum_set_virtual_threshold
- vacuum_split_segments
- vacuum_start_shortcut
eufy_security:
- alarm_arm_custom1
- alarm_arm_custom2
- alarm_arm_custom3
- alarm_off
- calibrate
- chime
- delete_preset_position
- force_sync
- generate_image
- geofence
- preset_position
- ptz
- ptz_360
- ptz_down
- ptz_left
- ptz_right
- ptz_up
- quick_response
- reboot
- reset_alarm
- save_preset_position
- schedule
- send_message
- set_log_level
- snooze
- start_p2p_livestream
- start_rtsp_livestream
- stop_p2p_livestream
- stop_rtsp_livestream
- trigger_base_alarm_with_duration
- trigger_camera_alarm_with_duration
fan:
- decrease_speed
- increase_speed
- oscillate
- set_direction
- set_percentage
- set_preset_mode
- toggle
- turn_off
- turn_on
ffmpeg:
- restart
- start
- stop
file:
- read_file
fritz:
- dial
- set_guest_wifi_password
frontend:
- reload_themes
- set_theme
google_generative_ai_conversation:
- generate_content
group:
- reload
- remove
- set
hassio:
- addon_restart
- addon_start
- addon_stdin
- addon_stop
- backup_full
- backup_partial
- host_reboot
- host_shutdown
- restore_full
- restore_partial
home_connect:
- change_setting
- set_program_and_options
homeassistant:
- check_config
- reload_all
- reload_config_entry
- reload_core_config
- reload_custom_templates
- restart
- save_persistent_states
- set_location
- stop
- toggle
- turn_off
- turn_on
- update_entity
humidifier:
- set_humidity
- set_mode
- toggle
- turn_off
- turn_on
image:
- snapshot
input_boolean:
- reload
- toggle
- turn_off
- turn_on
input_button:
- press
- reload
input_datetime:
- reload
- set_datetime
input_number:
- decrement
- increment
- reload
- set_value
input_select:
- reload
- select_first
- select_last
- select_next
- select_option
- select_previous
- set_options
input_text:
- reload
- set_value
light:
- toggle
- turn_off
- turn_on
lock:
- lock
- open
- unlock
logbook:
- log
logger:
- set_default_level
- set_level
matter:
- water_heater_boost
meross_lan:
- request
mqtt:
- dump
- publish
- reload
notify:
- mobile_app_alizas_iphone
- mobile_app_sadats_iphone_15_olx
- mobile_app_syed_sadats_ipad
- notify
- persistent_notification
- send_message
number:
- set_value
persistent_notification:
- create
- dismiss
- dismiss_all
person:
- reload
recorder:
- disable
- enable
- get_statistics
- purge
- purge_entities
scene:
- apply
- create
- delete
- reload
- turn_on
schedule:
- get_schedule
- reload
script:
- notify_all
- reload
- toggle
- turn_off
- turn_on
select:
- select_first
- select_last
- select_next
- select_option
- select_previous
shopping_list:
- add_item
- clear_completed_items
- complete_all
- complete_item
- incomplete_all
- incomplete_item
- remove_item
- sort
siren:
- toggle
- turn_off
- turn_on
switch:
- toggle
- turn_off
- turn_on
system_log:
- clear
- write
template:
- reload
text:
- set_value
time:
- set_value
timer:
- cancel
- change
- finish
- pause
- reload
- start
todo:
- add_item
- get_items
- remove_completed_items
- remove_item
- update_item
tts:
- clear_cache
- cloud_say
- speak
update:
- clear_skipped
- install
- skip
utility_meter:
- calibrate
- reset
vacuum:
- clean_spot
- locate
- pause
- return_to_base
- send_command
- set_fan_speed
- start
- stop
valve:
- close_valve
- open_valve
- set_valve_position
- stop_valve
- toggle
vicare:
- set_vicare_mode
water_heater:
- set_away_mode
- set_operation_mode
- set_temperature
- turn_off
- turn_on
weather:
- get_forecasts
webrtc:
- create_link
- dash_cast
yahoofinance:
- refresh_symbols
- reload
zone:
- reload
